function [ out ] = fold2split(fold,path)
%{
    Author : Vaibhav Malpani 
    Uni: vom2102
    Course: Biometrics CS6737
    Homework 5 - Face Verification using SIFT features in SVM classifier
    
    Splits dataset into training and test for a single fold.
    Iteratively call this function to build up training and test set.
    
    Parameters:
    fold - struct 
        pairs - having name of two faces to be compared
        labels - correct class (1 if correct 0 otherwise)
    path - path of the dataset (append '/facename/facename.jpg' to get file)
    out(1) - matrix with the first column corresponding to the class label
    out(2:end) - features generated by SIFT
%}
    class = fold.labels;
    duo = fold.pairs;
    out = [];
    for i = 1 : size(duo,1)
        cell2txt_img1 = duo(i,1);
        cell2txt_img2 = duo(i,2);
        out = [out ; genDescriptors(cell2txt_img1{1}, cell2txt_img2{1}, class(i), path)];
        if mod(i,50) == 0
            fprintf 'Generating SIFT Descriptors...\n'
        end
    end
end